theme: light

server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: 'set-via-env'

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain:
        - 'hydroponic.localhost'
        - 'grafana.hydroponic.localhost'
      policy: one_factor

session:
  secret: 'set-via-env'
  cookies:
    - domain: 'hydroponic.localhost'
      authelia_url: 'https://auth.hydroponic.localhost'
      default_redirection_url: 'https://hydroponic.localhost'
      name: 'authelia_session'
      expiration: '1h'
      inactivity: '5m'

storage:
  encryption_key: 'set-via-env'
  postgres:
    address: 'tcp://postgres:5432'
    database: authelia
    schema: public
    username: authelia

notifier:
  filesystem:
    filename: /data/notification.txt
