entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
  metrics:
    address: ':8082'

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false
  insecure: false

log:
  level: INFO

accessLog: {}
