http:
  routers:
    authelia:
      rule: "Host(`auth.hydroponic.localhost`)"
      entryPoints:
        - websecure
      service: authelia
      tls: {}

    dashboard-ws:
      rule: "Host(`hydroponic.localhost`) && PathPrefix(`/socket.io`)"
      entryPoints:
        - websecure
      service: dashboard-ws
      middlewares:
        - authelia
      priority: 100
      tls: {}

    frontend:
      rule: "Host(`hydroponic.localhost`)"
      entryPoints:
        - websecure
      service: frontend
      middlewares:
        - authelia
      priority: 10
      tls: {}

  services:
    authelia:
      loadBalancer:
        servers:
          - url: "http://authelia:9091"

    dashboard-ws:
      loadBalancer:
        servers:
          - url: "http://dashboard-api:3010"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend-web:3000"

  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
